// AUTO-GENERATED by scripts/fetch-reference-photos.mjs — do not edit by hand.
// Real industrial reference photography from Wikimedia Commons (commercial-use
// licenses). Each entry carries attribution required by its license.

export type ReferenceManifestEntry = {
  readonly src: string;
  readonly title: string;
  readonly credit: string;
  readonly source: string;
  readonly license: string;
  readonly licenseUrl: string;
};

export const REFERENCE_MANIFEST: Record<string, ReferenceManifestEntry> = {
  "svc-corte-laser": {
    "src": "/images/reference/services/svc-corte-laser.jpg",
    "title": "CNC Laser Cutting Machine in Operation at Martin Guitar Factory.jpg",
    "credit": "Henrysz",
    "source": "https://commons.wikimedia.org/wiki/File:CNC_Laser_Cutting_Machine_in_Operation_at_Martin_Guitar_Factory.jpg",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0"
  },
  "hero-workshop": {
    "src": "/images/reference/hero/hero-workshop.jpg",
    "title": "Laser Cutting.jpg",
    "credit": "Framos123",
    "source": "https://commons.wikimedia.org/wiki/File:Laser_Cutting.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "workshop-machinery": {
    "src": "/images/reference/workshop/workshop-machinery.jpg",
    "title": "Lathe Threaded Arbor With Bolt.jpg",
    "credit": "David English",
    "source": "https://commons.wikimedia.org/wiki/File:Lathe_Threaded_Arbor_With_Bolt.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "workshop-atmosphere": {
    "src": "/images/reference/workshop/workshop-atmosphere.jpg",
    "title": "Taig metal lathe, Drill press and Workbench.jpg",
    "credit": "James Bastow",
    "source": "https://commons.wikimedia.org/wiki/File:Taig_metal_lathe,_Drill_press_and_Workbench.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0"
  },
  "svc-fabricacion": {
    "src": "/images/reference/services/svc-fabricacion.jpg",
    "title": "Subsea template & docking pile guide (3467346422).jpg",
    "credit": "Vodka Hanoi",
    "source": "https://commons.wikimedia.org/wiki/File:Subsea_template_%26_docking_pile_guide_(3467346422).jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0"
  },
  "svc-paneles": {
    "src": "/images/reference/services/svc-paneles.jpg",
    "title": "Perforated metal sheet for ionize tubes.jpg",
    "credit": "BentaxGermany",
    "source": "https://commons.wikimedia.org/wiki/File:Perforated_metal_sheet_for_ionize_tubes.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"
  },
  "prod-paneles": {
    "src": "/images/reference/products/prod-paneles.jpg",
    "title": "Perforated steel.jpg",
    "credit": "Tahini",
    "source": "https://commons.wikimedia.org/wiki/File:Perforated_steel.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0"
  },
  "svc-celosias": {
    "src": "/images/reference/services/svc-celosias.jpg",
    "title": "Screen MET 61DCAT13R5.jpg",
    "credit": "Lockwood de Forest",
    "source": "https://commons.wikimedia.org/wiki/File:Screen_MET_61DCAT13R5.jpg",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en"
  },
  "prod-celosias": {
    "src": "/images/reference/products/prod-celosias.jpg",
    "title": "Screen MET DT182.jpg",
    "credit": "Lockwood de Forest",
    "source": "https://commons.wikimedia.org/wiki/File:Screen_MET_DT182.jpg",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en"
  },
  "svc-portones": {
    "src": "/images/reference/services/svc-portones.jpg",
    "title": "Wrought iron gate St Michael's church.jpg",
    "credit": "MauraWen",
    "source": "https://commons.wikimedia.org/wiki/File:Wrought_iron_gate_St_Michael%27s_church.jpg",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0"
  },
  "prod-portones": {
    "src": "/images/reference/products/prod-portones.jpg",
    "title": "Wrought iron gate from Germany, V&A London.jpg",
    "credit": "14GTR",
    "source": "https://commons.wikimedia.org/wiki/File:Wrought_iron_gate_from_Germany,_V%26A_London.jpg",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en"
  },
  "prod-rejas": {
    "src": "/images/reference/products/prod-rejas.jpg",
    "title": "Wrought iron gate, Patterdale, Ullswater.JPG",
    "credit": "Rosser1954",
    "source": "https://commons.wikimedia.org/wiki/File:Wrought_iron_gate,_Patterdale,_Ullswater.JPG",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "svc-soldadura": {
    "src": "/images/reference/services/svc-soldadura.jpg",
    "title": "GMAW.welding.af.ncs.jpg",
    "credit": "William M. Plate Jr.",
    "source": "https://commons.wikimedia.org/wiki/File:GMAW.welding.af.ncs.jpg",
    "license": "Public domain",
    "licenseUrl": ""
  },
  "svc-plegado": {
    "src": "/images/reference/services/svc-plegado.jpg",
    "title": "High-tonnage press brake.jpg",
    "credit": "GaspariniIndustries",
    "source": "https://commons.wikimedia.org/wiki/File:High-tonnage_press_brake.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "svc-cad": {
    "src": "/images/reference/services/svc-cad.jpg",
    "title": "Man using AutoCAD (1987).jpg",
    "credit": "Evergreen Systems",
    "source": "https://commons.wikimedia.org/wiki/File:Man_using_AutoCAD_(1987).jpg",
    "license": "Public domain",
    "licenseUrl": ""
  },
  "prod-piezas": {
    "src": "/images/reference/products/prod-piezas.png",
    "title": "CAD model and CNC machined part.PNG",
    "credit": "Mike1024",
    "source": "https://commons.wikimedia.org/wiki/File:CAD_model_and_CNC_machined_part.PNG",
    "license": "Public domain",
    "licenseUrl": ""
  },
  "prod-custom": {
    "src": "/images/reference/products/prod-custom.jpg",
    "title": "FLEX Program Drives Innovation at 52nd MXS (9317638).jpg",
    "credit": "U.S. Air Force photo by Airman 1st Class Gretchen McCarty",
    "source": "https://commons.wikimedia.org/wiki/File:FLEX_Program_Drives_Innovation_at_52nd_MXS_(9317638).jpg",
    "license": "Public domain",
    "licenseUrl": ""
  }
} as const;
